const roleKeywords = {
  "Frontend Web Developer": [
    "javascript",
    "css",
    "html",
    "react",
    "angular",
    "vue",
    "bootstrap",
    "jquery",
    "responsive design",
    "webpack",
    "babel",
    "typescript",
    "sass",
    "less",
    "Frontend Web Developer",
  ],
  "Backend Web Developer": [
    "nodejs",
    "express",
    "python",
    "django",
    "flask",
    "ruby",
    "rails",
    "php",
    "laravel",
    "mongodb",
    "postgresql",
    "mysql",
    "redis",
    "docker",
    "Backend Web Developer",
  ],
  "Full Stack Developer": [
    "javascript",
    "nodejs",
    "express",
    "react",
    "angular",
    "vue",
    "mongodb",
    "postgresql",
    "redis",
    "docker",
    "python",
    "django",
    "flask",
    "ruby",
    "Full Stack Developer",
  ],
  "DevOps Engineer": [
    "aws",
    "docker",
    "kubernetes",
    "jenkins",
    "terraform",
    "ansible",
    "linux",
    "bash",
    "python",
    "devops",
    "cloud",
    "azure",
    "gcp",
    "ci/cd",
    "DevOps Engineer",
  ],
  "Data Scientist": [
    "python",
    "r",
    "tensorflow",
    "keras",
    "pytorch",
    "pandas",
    "numpy",
    "scikit-learn",
    "statistics",
    "machine learning",
    "deep learning",
    "sql",
    "data visualization",
    "big data",
    "Data Scientist",
  ],
  "Machine Learning Engineer": [
    "python",
    "tensorflow",
    "keras",
    "pytorch",
    "machine learning",
    "deep learning",
    "nlp",
    "computer vision",
    "reinforcement learning",
    "scikit-learn",
    "pandas",
    "numpy",
    "aws",
    "azure",
    "Machine Learning Engineer",
  ],
  "Database Administrator": [
    "sql",
    "mysql",
    "postgresql",
    "mongodb",
    "cassandra",
    "oracle",
    "database",
    "nosql",
    "data migration",
    "performance tuning",
    "database security",
    "database design",
    "data warehousing",
    "etl",
    "Database Administrator",
  ],
  "System Administrator": [
    "linux",
    "windows",
    "bash",
    "powershell",
    "networking",
    "vmware",
    "active directory",
    "system administration",
    "security",
    "cloud",
    "aws",
    "azure",
    "gcp",
    "docker",
    "System Administrator",
  ],
  "Network Engineer": [
    "cisco",
    "juniper",
    "routing",
    "switching",
    "vpn",
    "firewall",
    "tcp/ip",
    "network security",
    "wan",
    "lan",
    "ccna",
    "ccnp",
    "network troubleshooting",
    "network design",
    "Network Engineer",
  ],
  "Security Analyst": [
    "cybersecurity",
    "cissp",
    "cism",
    "penetration testing",
    "firewall",
    "encryption",
    "security policies",
    "risk assessment",
    "incident response",
    "network security",
    "computer forensics",
    "intrusion detection",
    "malware analysis",
    "Security Analyst",
  ],
  "UX/UI Designer": [
    "sketch",
    "invision",
    "photoshop",
    "illustrator",
    "figma",
    "user experience",
    "user interface",
    "wireframing",
    "prototyping",
    "responsive design",
    "color theory",
    "typography",
    "user research",
    "UX/UI Designer",
  ],
  "QA Engineer": [
    "testing",
    "selenium",
    "junit",
    "python",
    "java",
    "automation",
    "performance testing",
    "agile",
    "bug tracking",
    "jira",
    "test cases",
    "black box testing",
    "white box testing",
    "QA Engineer",
  ],
  "Mobile App Developer": [
    "swift",
    "kotlin",
    "java",
    "ios",
    "android",
    "react native",
    "flutter",
    "xamarin",
    "cordova",
    "mobile ui",
    "firebase",
    "api",
    "sdk",
    "Mobile App Developer",
  ],
  "Data Engineer": [
    "python",
    "java",
    "scala",
    "hadoop",
    "spark",
    "kafka",
    "hive",
    "sql",
    "nosql",
    "aws",
    "azure",
    "gcp",
    "etl",
    "big data",
    "Data Engineer",
  ],
  "IT Support Specialist": [
    "troubleshooting",
    "windows",
    "macos",
    "linux",
    "networking",
    "helpdesk",
    "customer service",
    "hardware",
    "software",
    "remote support",
    "active directory",
    "security",
    "ITIL",
    "IT Support Specialist",
  ],
}
function calculateRoleScores(resumeText) {
  const scores = {}
  let totalKeywords = 0

  for (const role in roleKeywords) {
    let count = 0
    const keywords = roleKeywords[role]

    keywords.forEach((keyword) => {
      const regex = new RegExp("\\b" + keyword + "\\b", "gi")
      const keywordCount = (resumeText.match(regex) || []).length
      count += keywordCount
      totalKeywords += keywordCount
    })

    scores[role] = count
  }

  if (totalKeywords > 0) {
    for (const role in scores) {
      scores[role] /= totalKeywords
    }
  }

  return scores
}

module.exports = {
  calculateRoleScores,
}
